import type { Metadata } from "next";

import "./globals.css";

import { Toaster } from "sonner";
import { ReduxProvider } from "@/providers/Redux.provider";
import BootstrapAuth from "@/components/features/auth/BoostrapAuth";
import { Suspense } from "react";

export const metadata: Metadata = {
  title: "ZOZO Pet's Service",
  description: "Generated by create next app",
  icons: {
    icon: "/images/icons/Logo.webp",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={` font-normal antialiased bg-background-dark `}>
        <Suspense fallback={null}>
          <ReduxProvider>
            <Toaster richColors position="top-left" />
            {children}
            <BootstrapAuth />
          </ReduxProvider>
        </Suspense>
      </body>
    </html>
  );
}
