import type { Metadata } from "next";

import "../globals.css";

import NavBar from "../../components/layout/NavBar";

import { SidebarContextProvider } from "@/context/SidebarContext";
import Sidebar from "@/components/layout/SideBar";
import { ThemeProvider } from "@/providers/theme.provider";
import Footer from "@/components/layout/Footer";
import ReactQueryProvider from "@/providers/ReactQuery.provider";

export const metadata: Metadata = {
  title: "ZOZO Pet's Service",
  description: "Generated by create next app",
  icons: {
    icon: "/images/icons/Logo.webp",
  },
};

export default function HomeLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div
      className={` font-normal antialiased bg-background-light dark:bg-background-dark  transition-all  duration-700 `}
    >
      <ReactQueryProvider>
        <ThemeProvider>
          {" "}
          <SidebarContextProvider>
            <NavBar />

            <Sidebar />
          </SidebarContextProvider>
          <div className="min-h-screen"> {children}</div>
          <Footer />
        </ThemeProvider>
      </ReactQueryProvider>
    </div>
  );
}
